<?php
	require $_SERVER['DOCUMENT_ROOT'] . "/Gitco2/percorsi.php";
		
	include CLASSI . "/comuni.php";
	include CLASSI . "/anagrafe.php";
	include CLASSI . "/290.php";
	include CLASSI . "/ruolo.php";
	include CLASSI . "/coazione.php";

	set_time_limit(500);

//$tbody = '<tbody>
//<tr class="odd">
//<td title="Porta" class="zentriert rueckennummer bg_Torwart"><div class=rn_nummer>1</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/44058-1454084157.jpg?lm=1454084165" data-original="https://tmssl.akamaized.net//images/portrait/small/44058-1454084157.jpg?lm=1454084165" title="Wojciech Szczesny" alt="Wojciech Szczesny" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Wojciech Szczesny" class="spielprofil_tooltip" id="44058" href="/wojciech-szczesny/profil/spieler/44058">Wojciech Szczesny</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Wojciech Szczesny" class="spielprofil_tooltip" id="44058" href="/wojciech-szczesny/profil/spieler/44058">W. Szczesny</a></span></div></td></tr><tr><td>Portiere</td></tr></table></td><td class="hide" itemprop="athlete">Wojciech Szczesny</td><td class="zentriert">18/apr/1990 (29)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/135.png?lm=1520611569" title="Polonia" alt="Polonia" class="flaggenrahmen" /></td><td class="rechts hauptlink">35,00 mln € <span title="Valore di mercato precedente: 30,00 mln €" class="icons_sprite green-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Porta" class="zentriert rueckennummer bg_Torwart"><div class=rn_nummer>22</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/110923-1563474080.jpg?lm=1563474099" data-original="https://tmssl.akamaized.net//images/portrait/small/110923-1563474080.jpg?lm=1563474099" title="Mattia Perin" alt="Mattia Perin" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Mattia Perin" class="spielprofil_tooltip" id="110923" href="/mattia-perin/profil/spieler/110923">Mattia Perin</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Mattia Perin" class="spielprofil_tooltip" id="110923" href="/mattia-perin/profil/spieler/110923">M. Perin</a></span></div><span title="Infortunio alla spalla - Probabile ritorno 18/nov/2019" class="verletzt-table icons_sprite">&nbsp;</span></td></tr><tr><td>Portiere</td></tr></table></td><td class="hide" itemprop="athlete">Mattia Perin</td><td class="zentriert">10/nov/1992 (26)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">13,00 mln € <span title="Valore di mercato precedente: 15,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Porta" class="zentriert rueckennummer bg_Torwart"><div class=rn_nummer>77</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: FC Paris Saint-Germain; Data: 04/lug/2019; Riscatto: gratuito" href="/fc-paris-saint-germain/startseite/verein/583/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/583.png?lm=1522312728" title="Acquisto da: FC Paris Saint-Germain; Data: 04/lug/2019; Riscatto: gratuito" alt="FC Paris Saint-Germain" class="" /></a></span><a title="Acquisto da: FC Paris Saint-Germain; Data: 04/lug/2019; Riscatto: gratuito" class="hide-for-small" href="/fc-paris-saint-germain/startseite/verein/583/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/5023-1448530267.jpg?lm=1448530280" data-original="https://tmssl.akamaized.net//images/portrait/small/5023-1448530267.jpg?lm=1448530280" title="Gianluigi Buffon" alt="Gianluigi Buffon" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Gianluigi Buffon" class="spielprofil_tooltip" id="5023" href="/gianluigi-buffon/profil/spieler/5023">Gianluigi Buffon</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Gianluigi Buffon" class="spielprofil_tooltip" id="5023" href="/gianluigi-buffon/profil/spieler/5023">G. Buffon</a></span></div></td></tr><tr><td>Portiere</td></tr></table></td><td class="hide" itemprop="athlete">Gianluigi Buffon</td><td class="zentriert">28/gen/1978 (41)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">1,00 mln € <span title="Valore di mercato precedente: 1,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Porta" class="zentriert rueckennummer bg_Torwart"><div class=rn_nummer>31</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/75411-1468926569.jpg?lm=1468926578" data-original="https://tmssl.akamaized.net//images/portrait/small/75411-1468926569.jpg?lm=1468926578" title="Carlo Pinsoglio" alt="Carlo Pinsoglio" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Carlo Pinsoglio" class="spielprofil_tooltip" id="75411" href="/carlo-pinsoglio/profil/spieler/75411">Carlo Pinsoglio</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Carlo Pinsoglio" class="spielprofil_tooltip" id="75411" href="/carlo-pinsoglio/profil/spieler/75411">C. Pinsoglio</a></span></div></td></tr><tr><td>Portiere</td></tr></table></td><td class="hide" itemprop="athlete">Carlo Pinsoglio</td><td class="zentriert">16/mar/1990 (29)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">500 mila € <span title="Valore di mercato precedente: 500 mila €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>4</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: Ajax Amsterdam; Data: 18/lug/2019; Riscatto: 85,50 mln €" href="/ajax-amsterdam/startseite/verein/610/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/610.png?lm=1458894971" title="Acquisto da: Ajax Amsterdam; Data: 18/lug/2019; Riscatto: 85,50 mln €" alt="Ajax Amsterdam" class="" /></a></span><a title="Acquisto da: Ajax Amsterdam; Data: 18/lug/2019; Riscatto: 85,50 mln €" class="hide-for-small" href="/ajax-amsterdam/startseite/verein/610/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/326031-1522158497.jpg?lm=1522158506" data-original="https://tmssl.akamaized.net//images/portrait/small/326031-1522158497.jpg?lm=1522158506" title="Matthijs de Ligt" alt="Matthijs de Ligt" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Matthijs de Ligt" class="spielprofil_tooltip" id="326031" href="/matthijs-de-ligt/profil/spieler/326031">Matthijs de Ligt</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Matthijs de Ligt" class="spielprofil_tooltip" id="326031" href="/matthijs-de-ligt/profil/spieler/326031">M. de Ligt</a></span></div></td></tr><tr><td>Difensore centrale</td></tr></table></td><td class="hide" itemprop="athlete">Matthijs de Ligt</td><td class="zentriert">12/ago/1999 (20)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/122.png?lm=1520611569" title="Olanda" alt="Olanda" class="flaggenrahmen" /></td><td class="rechts hauptlink">75,00 mln € <span title="Valore di mercato precedente: 70,00 mln €" class="icons_sprite green-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>19</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/39983-1448464012.jpg?lm=1448464025" data-original="https://tmssl.akamaized.net//images/portrait/small/39983-1448464012.jpg?lm=1448464025" title="Leonardo Bonucci" alt="Leonardo Bonucci" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Leonardo Bonucci" class="spielprofil_tooltip" id="39983" href="/leonardo-bonucci/profil/spieler/39983">Leonardo Bonucci</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Leonardo Bonucci" class="spielprofil_tooltip" id="39983" href="/leonardo-bonucci/profil/spieler/39983">L. Bonucci</a></span></div></td></tr><tr><td>Difensore centrale</td></tr></table></td><td class="hide" itemprop="athlete">Leonardo Bonucci</td><td class="zentriert">01/mag/1987 (32)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">28,00 mln € <span title="Valore di mercato precedente: 35,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>24</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/162959-1418136957.jpg?lm=1433143751" data-original="https://tmssl.akamaized.net//images/portrait/small/162959-1418136957.jpg?lm=1433143751" title="Daniele Rugani" alt="Daniele Rugani" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Daniele Rugani" class="spielprofil_tooltip" id="162959" href="/daniele-rugani/profil/spieler/162959">Daniele Rugani</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Daniele Rugani" class="spielprofil_tooltip" id="162959" href="/daniele-rugani/profil/spieler/162959">D. Rugani</a></span></div></td></tr><tr><td>Difensore centrale</td></tr></table></td><td class="hide" itemprop="athlete">Daniele Rugani</td><td class="zentriert">29/lug/1994 (25)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">22,00 mln € <span title="Valore di mercato precedente: 22,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>28</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: US Sassuolo; Data: 05/lug/2019; Riscatto: 18,00 mln €" href="/us-sassuolo/startseite/verein/6574/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/6574.png?lm=1438548058" title="Acquisto da: US Sassuolo; Data: 05/lug/2019; Riscatto: 18,00 mln €" alt="US Sassuolo" class="" /></a></span><a title="Acquisto da: US Sassuolo; Data: 05/lug/2019; Riscatto: 18,00 mln €" class="hide-for-small" href="/us-sassuolo/startseite/verein/6574/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/340879-1547804821.jpg?lm=1547804828" data-original="https://tmssl.akamaized.net//images/portrait/small/340879-1547804821.jpg?lm=1547804828" title="Merih Demiral" alt="Merih Demiral" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Merih Demiral" class="spielprofil_tooltip" id="340879" href="/merih-demiral/profil/spieler/340879">Merih Demiral</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Merih Demiral" class="spielprofil_tooltip" id="340879" href="/merih-demiral/profil/spieler/340879">M. Demiral</a></span></div></td></tr><tr><td>Difensore centrale</td></tr></table></td><td class="hide" itemprop="athlete">Merih Demiral</td><td class="zentriert">05/mar/1998 (21)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/174.png?lm=1520611569" title="Turchia" alt="Turchia" class="flaggenrahmen" /></td><td class="rechts hauptlink">15,00 mln € <span title="Valore di mercato precedente: 5,00 mln €" class="icons_sprite green-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>3</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/29260-1448464153.jpg?lm=1448464171" data-original="https://tmssl.akamaized.net//images/portrait/small/29260-1448464153.jpg?lm=1448464171" title="Giorgio Chiellini" alt="Giorgio Chiellini" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Giorgio Chiellini" class="spielprofil_tooltip" id="29260" href="/giorgio-chiellini/profil/spieler/29260">Giorgio Chiellini</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Giorgio Chiellini" class="spielprofil_tooltip" id="29260" href="/giorgio-chiellini/profil/spieler/29260">G. Chiellini</a></span></div><span title="Capitano" class="kapitaenicon-table icons_sprite">&nbsp;</span></td></tr><tr><td>Difensore centrale</td></tr></table></td><td class="hide" itemprop="athlete">Giorgio Chiellini</td><td class="zentriert">14/ago/1984 (35)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">7,50 mln € <span title="Valore di mercato precedente: 10,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>12</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/79960-1474296962.jpg?lm=1474296972" data-original="https://tmssl.akamaized.net//images/portrait/small/79960-1474296962.jpg?lm=1474296972" title="Alex Sandro" alt="Alex Sandro" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Alex Sandro" class="spielprofil_tooltip" id="79960" href="/alex-sandro/profil/spieler/79960">Alex Sandro</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Alex Sandro" class="spielprofil_tooltip" id="79960" href="/alex-sandro/profil/spieler/79960">Alex Sandro</a></span></div></td></tr><tr><td>Terzino sinistro</td></tr></table></td><td class="hide" itemprop="athlete">Alex Sandro</td><td class="zentriert">26/gen/1991 (28)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/26.png?lm=1520611569" title="Brasile" alt="Brasile" class="flaggenrahmen" /></td><td class="rechts hauptlink">45,00 mln € <span title="Valore di mercato precedente: 50,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>13</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: Manchester City; Data: 07/ago/2019; Riscatto: 37,00 mln €" href="/manchester-city/startseite/verein/281/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/281.png?lm=1467356331" title="Acquisto da: Manchester City; Data: 07/ago/2019; Riscatto: 37,00 mln €" alt="Manchester City" class="" /></a></span><a title="Acquisto da: Manchester City; Data: 07/ago/2019; Riscatto: 37,00 mln €" class="hide-for-small" href="/manchester-city/startseite/verein/281/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/145707-1462894787.jpg?lm=1462894805" data-original="https://tmssl.akamaized.net//images/portrait/small/145707-1462894787.jpg?lm=1462894805" title="Danilo" alt="Danilo" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Danilo" class="spielprofil_tooltip" id="145707" href="/danilo/profil/spieler/145707">Danilo</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Danilo" class="spielprofil_tooltip" id="145707" href="/danilo/profil/spieler/145707">Danilo</a></span></div></td></tr><tr><td>Terzino destro</td></tr></table></td><td class="hide" itemprop="athlete">Danilo</td><td class="zentriert">15/lug/1991 (28)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/26.png?lm=1520611569" title="Brasile" alt="Brasile" class="flaggenrahmen" /></td><td class="rechts hauptlink">20,00 mln € <span title="Valore di mercato precedente: 20,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Difesa" class="zentriert rueckennummer bg_Abwehr"><div class=rn_nummer>2</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/88682-1455536736.jpg?lm=1455536752" data-original="https://tmssl.akamaized.net//images/portrait/small/88682-1455536736.jpg?lm=1455536752" title="Mattia De Sciglio" alt="Mattia De Sciglio" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Mattia De Sciglio" class="spielprofil_tooltip" id="88682" href="/mattia-de-sciglio/profil/spieler/88682">Mattia De Sciglio</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Mattia De Sciglio" class="spielprofil_tooltip" id="88682" href="/mattia-de-sciglio/profil/spieler/88682">M. De Sciglio</a></span></div></td></tr><tr><td>Terzino destro</td></tr></table></td><td class="hide" itemprop="athlete">Mattia De Sciglio</td><td class="zentriert">20/ott/1992 (26)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">14,00 mln € <span title="Valore di mercato precedente: 14,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>23</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/119296-1567162394.jpg?lm=1567162414" data-original="https://tmssl.akamaized.net//images/portrait/small/119296-1567162394.jpg?lm=1567162414" title="Emre Can" alt="Emre Can" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Emre Can" class="spielprofil_tooltip" id="119296" href="/emre-can/profil/spieler/119296">Emre Can</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Emre Can" class="spielprofil_tooltip" id="119296" href="/emre-can/profil/spieler/119296">Emre Can</a></span></div></td></tr><tr><td>Mediano</td></tr></table></td><td class="hide" itemprop="athlete">Emre Can</td><td class="zentriert">12/gen/1994 (25)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/40.png?lm=1520612525" title="Germania" alt="Germania" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/174.png?lm=1520611569" title="Turchia" alt="Turchia" class="flaggenrahmen" /></td><td class="rechts hauptlink">40,00 mln € <span title="Valore di mercato precedente: 30,00 mln €" class="icons_sprite green-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>5</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/44162-1567161979.png?lm=1567162015" data-original="https://tmssl.akamaized.net//images/portrait/small/44162-1567161979.png?lm=1567162015" title="Miralem Pjanic" alt="Miralem Pjanic" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Miralem Pjanic" class="spielprofil_tooltip" id="44162" href="/miralem-pjanic/profil/spieler/44162">Miralem Pjanic</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Miralem Pjanic" class="spielprofil_tooltip" id="44162" href="/miralem-pjanic/profil/spieler/44162">M. Pjanic</a></span></div></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Miralem Pjanic</td><td class="zentriert">02/apr/1990 (29)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/24.png?lm=1520611569" title="Bosnia-Erzegovina" alt="Bosnia-Erzegovina" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/99.png?lm=1520611569" title="Lussemburgo" alt="Lussemburgo" class="flaggenrahmen" /></td><td class="rechts hauptlink">70,00 mln € <span title="Valore di mercato precedente: 70,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>8</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: FC Arsenal; Data: 01/lug/2019; Riscatto: gratuito" href="/fc-arsenal/startseite/verein/11/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/11.png?lm=1489787850" title="Acquisto da: FC Arsenal; Data: 01/lug/2019; Riscatto: gratuito" alt="FC Arsenal" class="" /></a></span><a title="Acquisto da: FC Arsenal; Data: 01/lug/2019; Riscatto: gratuito" class="hide-for-small" href="/fc-arsenal/startseite/verein/11/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/50057-1518795716.jpg?lm=1518795731" data-original="https://tmssl.akamaized.net//images/portrait/small/50057-1518795716.jpg?lm=1518795731" title="Aaron Ramsey" alt="Aaron Ramsey" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Aaron Ramsey" class="spielprofil_tooltip" id="50057" href="/aaron-ramsey/profil/spieler/50057">Aaron Ramsey</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Aaron Ramsey" class="spielprofil_tooltip" id="50057" href="/aaron-ramsey/profil/spieler/50057">A. Ramsey</a></span></div><span title="Lombalgia - Ritorno sconosciuto" class="verletzt-table icons_sprite">&nbsp;</span></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Aaron Ramsey</td><td class="zentriert">26/dic/1990 (28)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/191.png?lm=1520611569" title="Galles" alt="Galles" class="flaggenrahmen" /></td><td class="rechts hauptlink">40,00 mln € <span title="Valore di mercato precedente: 40,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>25</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Acquisto da: FC Paris Saint-Germain; Data: 01/lug/2019; Riscatto: gratuito" href="/fc-paris-saint-germain/startseite/verein/583/saison_id/2019"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/583.png?lm=1522312728" title="Acquisto da: FC Paris Saint-Germain; Data: 01/lug/2019; Riscatto: gratuito" alt="FC Paris Saint-Germain" class="" /></a></span><a title="Acquisto da: FC Paris Saint-Germain; Data: 01/lug/2019; Riscatto: gratuito" class="hide-for-small" href="/fc-paris-saint-germain/startseite/verein/583/saison_id/2019"><img src="/images/icons/zugang_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/182913-1548523339.jpg?lm=1548523382" data-original="https://tmssl.akamaized.net//images/portrait/small/182913-1548523339.jpg?lm=1548523382" title="Adrien Rabiot" alt="Adrien Rabiot" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Adrien Rabiot" class="spielprofil_tooltip" id="182913" href="/adrien-rabiot/profil/spieler/182913">Adrien Rabiot</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Adrien Rabiot" class="spielprofil_tooltip" id="182913" href="/adrien-rabiot/profil/spieler/182913">A. Rabiot</a></span></div></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Adrien Rabiot</td><td class="zentriert">03/apr/1995 (24)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/50.png?lm=1520611569" title="Francia" alt="Francia" class="flaggenrahmen" /></td><td class="rechts hauptlink">35,00 mln € <span title="Valore di mercato precedente: 35,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>30</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/354362-1461141874.jpg?lm=1461141895" data-original="https://tmssl.akamaized.net//images/portrait/small/354362-1461141874.jpg?lm=1461141895" title="Rodrigo Bentancur" alt="Rodrigo Bentancur" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Rodrigo Bentancur" class="spielprofil_tooltip" id="354362" href="/rodrigo-bentancur/profil/spieler/354362">Rodrigo Bentancur</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Rodrigo Bentancur" class="spielprofil_tooltip" id="354362" href="/rodrigo-bentancur/profil/spieler/354362">R. Bentancur</a></span></div></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Rodrigo Bentancur</td><td class="zentriert">25/giu/1997 (22)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/179.png?lm=1520611569" title="Uruguay" alt="Uruguay" class="flaggenrahmen" /></td><td class="rechts hauptlink">35,00 mln € <span title="Valore di mercato precedente: 35,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>14</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/33923-1454670291.jpg?lm=1454670290" data-original="https://tmssl.akamaized.net//images/portrait/small/33923-1454670291.jpg?lm=1454670290" title="Blaise Matuidi" alt="Blaise Matuidi" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Blaise Matuidi" class="spielprofil_tooltip" id="33923" href="/blaise-matuidi/profil/spieler/33923">Blaise Matuidi</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Blaise Matuidi" class="spielprofil_tooltip" id="33923" href="/blaise-matuidi/profil/spieler/33923">B. Matuidi</a></span></div></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Blaise Matuidi</td><td class="zentriert">09/apr/1987 (32)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/50.png?lm=1520611569" title="Francia" alt="Francia" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/6.png?lm=1520611569" title="Angola" alt="Angola" class="flaggenrahmen" /></td><td class="rechts hauptlink">22,00 mln € <span title="Valore di mercato precedente: 30,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Centrocampo" class="zentriert rueckennummer bg_Mittelfeld"><div class=rn_nummer>6</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/29401-1503327624.jpg?lm=1503327673" data-original="https://tmssl.akamaized.net//images/portrait/small/29401-1503327624.jpg?lm=1503327673" title="Sami Khedira" alt="Sami Khedira" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Sami Khedira" class="spielprofil_tooltip" id="29401" href="/sami-khedira/profil/spieler/29401">Sami Khedira</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Sami Khedira" class="spielprofil_tooltip" id="29401" href="/sami-khedira/profil/spieler/29401">S. Khedira</a></span></div></td></tr><tr><td>Centrale</td></tr></table></td><td class="hide" itemprop="athlete">Sami Khedira</td><td class="zentriert">04/apr/1987 (32)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/40.png?lm=1520612525" title="Germania" alt="Germania" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/173.png?lm=1520611569" title="Tunisia" alt="Tunisia" class="flaggenrahmen" /></td><td class="rechts hauptlink">7,00 mln € <span title="Valore di mercato precedente: 15,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>7</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/8198-1515761767.jpg?lm=1515761786" data-original="https://tmssl.akamaized.net//images/portrait/small/8198-1515761767.jpg?lm=1515761786" title="Cristiano Ronaldo" alt="Cristiano Ronaldo" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Cristiano Ronaldo" class="spielprofil_tooltip" id="8198" href="/cristiano-ronaldo/profil/spieler/8198">Cristiano Ronaldo</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Cristiano Ronaldo" class="spielprofil_tooltip" id="8198" href="/cristiano-ronaldo/profil/spieler/8198">Cristiano Ronaldo</a></span></div></td></tr><tr><td>Ala sinistra</td></tr></table></td><td class="hide" itemprop="athlete">Cristiano Ronaldo</td><td class="zentriert">05/feb/1985 (34)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/136.png?lm=1520611569" title="Portogallo" alt="Portogallo" class="flaggenrahmen" /></td><td class="rechts hauptlink">90,00 mln € <span title="Valore di mercato precedente: 100,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>15</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Ritorno prestito da: ACF Fiorentina; Data: 30/giu/2019; Riscatto: Fine prestito" href="/acf-fiorentina/startseite/verein/430/saison_id/2018"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/430.png?lm=1520933432" title="Ritorno prestito da: ACF Fiorentina; Data: 30/giu/2019; Riscatto: Fine prestito" alt="ACF Fiorentina" class="" /></a></span><a title="Ritorno prestito da: ACF Fiorentina; Data: 30/giu/2019; Riscatto: Fine prestito" class="hide-for-small" href="/acf-fiorentina/startseite/verein/430/saison_id/2018"><img src="/images/icons/rueckkehr_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/205940-1454598632.jpg?lm=1454598638" data-original="https://tmssl.akamaized.net//images/portrait/small/205940-1454598632.jpg?lm=1454598638" title="Marko Pjaca" alt="Marko Pjaca" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Marko Pjaca" class="spielprofil_tooltip" id="205940" href="/marko-pjaca/profil/spieler/205940">Marko Pjaca</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Marko Pjaca" class="spielprofil_tooltip" id="205940" href="/marko-pjaca/profil/spieler/205940">M. Pjaca</a></span></div><span title="Rottura del legamento crociato - Probabile ritorno 01/ott/2019" class="verletzt-table icons_sprite">&nbsp;</span></td></tr><tr><td>Ala sinistra</td></tr></table></td><td class="hide" itemprop="athlete">Marko Pjaca</td><td class="zentriert">06/mag/1995 (24)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/37.png?lm=1520611569" title="Croazia" alt="Croazia" class="flaggenrahmen" /></td><td class="rechts hauptlink">10,00 mln € <span title="Valore di mercato precedente: 10,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="even">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>33</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/197300-1448528133.jpg?lm=1448528151" data-original="https://tmssl.akamaized.net//images/portrait/small/197300-1448528133.jpg?lm=1448528151" title="Federico Bernardeschi" alt="Federico Bernardeschi" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Federico Bernardeschi" class="spielprofil_tooltip" id="197300" href="/federico-bernardeschi/profil/spieler/197300">Federico Bernardeschi</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Federico Bernardeschi" class="spielprofil_tooltip" id="197300" href="/federico-bernardeschi/profil/spieler/197300">F. Bernardeschi</a></span></div></td></tr><tr><td>Ala destra</td></tr></table></td><td class="hide" itemprop="athlete">Federico Bernardeschi</td><td class="zentriert">16/feb/1994 (25)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">45,00 mln € <span title="Valore di mercato precedente: 45,00 mln €" class="icons_sprite grey-block-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>11</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/75615-1537176773.jpg?lm=1537176797" data-original="https://tmssl.akamaized.net//images/portrait/small/75615-1537176773.jpg?lm=1537176797" title="Douglas Costa" alt="Douglas Costa" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Douglas Costa" class="spielprofil_tooltip" id="75615" href="/douglas-costa/profil/spieler/75615">Douglas Costa</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Douglas Costa" class="spielprofil_tooltip" id="75615" href="/douglas-costa/profil/spieler/75615">D. Costa</a></span></div></td></tr><tr><td>Ala destra</td></tr></table></td><td class="hide" itemprop="athlete">Douglas Costa</td><td class="zentriert">14/set/1990 (28)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/26.png?lm=1520611569" title="Brasile" alt="Brasile" class="flaggenrahmen" /></td><td class="rechts hauptlink">38,00 mln € <span title="Valore di mercato precedente: 45,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>16</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/91970-1495526495.jpg?lm=1495526521" data-original="https://tmssl.akamaized.net//images/portrait/small/91970-1495526495.jpg?lm=1495526521" title="Juan Cuadrado" alt="Juan Cuadrado" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Juan Cuadrado" class="spielprofil_tooltip" id="91970" href="/juan-cuadrado/profil/spieler/91970">Juan Cuadrado</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Juan Cuadrado" class="spielprofil_tooltip" id="91970" href="/juan-cuadrado/profil/spieler/91970">J. Cuadrado</a></span></div></td></tr><tr><td>Ala destra</td></tr></table></td><td class="hide" itemprop="athlete">Juan Cuadrado</td><td class="zentriert">26/mag/1988 (31)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/83.png?lm=1520611569" title="Colombia" alt="Colombia" class="flaggenrahmen" /></td><td class="rechts hauptlink">18,00 mln € <span title="Valore di mercato precedente: 25,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>10</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/206050-1541076083.jpg?lm=1541076105" data-original="https://tmssl.akamaized.net//images/portrait/small/206050-1541076083.jpg?lm=1541076105" title="Paulo Dybala" alt="Paulo Dybala" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Paulo Dybala" class="spielprofil_tooltip" id="206050" href="/paulo-dybala/profil/spieler/206050">Paulo Dybala</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Paulo Dybala" class="spielprofil_tooltip" id="206050" href="/paulo-dybala/profil/spieler/206050">P. Dybala</a></span></div></td></tr><tr><td>Seconda punta</td></tr></table></td><td class="hide" itemprop="athlete">Paulo Dybala</td><td class="zentriert">15/nov/1993 (25)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/9.png?lm=1520611569" title="Argentina" alt="Argentina" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/75.png?lm=1520611569" title="Italia" alt="Italia" class="flaggenrahmen" /></td><td class="rechts hauptlink">85,00 mln € <span title="Valore di mercato precedente: 100,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="even">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>21</div></td><td title="" class="posrela"><span class="wechsel-kader-wappen hide-for-small"><a title="Ritorno prestito da: Chelsea FC; Data: 30/giu/2019; Riscatto: Fine prestito" href="/chelsea-fc/startseite/verein/631/saison_id/2018"><img src="https://tmssl.akamaized.net//images/wappen/kaderquad/631.png?lm=1444558831" title="Ritorno prestito da: Chelsea FC; Data: 30/giu/2019; Riscatto: Fine prestito" alt="Chelsea FC" class="" /></a></span><a title="Ritorno prestito da: Chelsea FC; Data: 30/giu/2019; Riscatto: Fine prestito" class="hide-for-small" href="/chelsea-fc/startseite/verein/631/saison_id/2018"><img src="/images/icons/rueckkehr_beta_kader.png" class="wechsel-symbol" width="19px" height="19px" /></a><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/39153-1476439911.jpg?lm=1476439924" data-original="https://tmssl.akamaized.net//images/portrait/small/39153-1476439911.jpg?lm=1476439924" title="Gonzalo Higuaín" alt="Gonzalo Higuaín" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Gonzalo Higuaín" class="spielprofil_tooltip" id="39153" href="/gonzalo-higuain/profil/spieler/39153">Gonzalo Higuaín</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Gonzalo Higuaín" class="spielprofil_tooltip" id="39153" href="/gonzalo-higuain/profil/spieler/39153">G. Higuaín</a></span></div></td></tr><tr><td>Punta centrale</td></tr></table></td><td class="hide" itemprop="athlete">Gonzalo Higuaín</td><td class="zentriert">10/dic/1987 (31)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/9.png?lm=1520611569" title="Argentina" alt="Argentina" class="flaggenrahmen" /><br /><img src="https://tmssl.akamaized.net//images/flagge/verysmall/50.png?lm=1520611569" title="Francia" alt="Francia" class="flaggenrahmen" /></td><td class="rechts hauptlink">35,00 mln € <span title="Valore di mercato precedente: 45,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//<tr class="odd">
//<td title="Attaccante" class="zentriert rueckennummer bg_Sturm"><div class=rn_nummer>17</div></td><td title="" class="posrela"><table class="inline-table" title=><tr><td rowspan="2" class=""><a href="#"><img data-src="https://tmssl.akamaized.net//images/portrait/small/34572-1448465837.jpg?lm=1448465855" data-original="https://tmssl.akamaized.net//images/portrait/small/34572-1448465837.jpg?lm=1448465855" title="Mario Mandzukic" alt="Mario Mandzukic" class="bilderrahmen-fixed lazy lazy" /></a></td><td class="hauptlink"><div class="di nowrap"><span class="hide-for-small"><a title="Mario Mandzukic" class="spielprofil_tooltip" id="34572" href="/mario-mandzukic/profil/spieler/34572">Mario Mandzukic</a></span></div><div class="di nowrap"><span class="show-for-small"><a title="Mario Mandzukic" class="spielprofil_tooltip" id="34572" href="/mario-mandzukic/profil/spieler/34572">M. Mandzukic</a></span></div></td></tr><tr><td>Punta centrale</td></tr></table></td><td class="hide" itemprop="athlete">Mario Mandzukic</td><td class="zentriert">21/mag/1986 (33)</td><td class="zentriert "><img src="https://tmssl.akamaized.net//images/flagge/verysmall/37.png?lm=1520611569" title="Croazia" alt="Croazia" class="flaggenrahmen" /></td><td class="rechts hauptlink">18,00 mln € <span title="Valore di mercato precedente: 25,00 mln €" class="icons_sprite red-arrow-ten"> </span></td></tr>
//</tbody>';

preg_match_all('#<img data-src(.*?)</td>#i',$tbody,$players);

$a_players = array();
$count=0;
for($i=0;$i<count($players[0]);$i++){
    $player = explode('"',$players[1][$i]);
        $a_players[$count]["Name"] = $player[5];
        $a_players[$count]["Url"] = $player[1];
        $count++;
}

print_r($a_players);



//	mysql_query('BEGIN');
//
//    $query = "SELECT * FROM enti_gestiti WHERE Autorizzazione=3 AND CC!='A072' ORDER BY CC ASC";
//    $result = mysql_query($query);
//    $query = "SELECT * FROM parametri_generali WHERE CC='A072' AND Tipo_Riscossione='PUBBLICITA' ";
//    $result2 = mysql_query($query);
//    $resultPar = mysql_fetch_array($result2,MYSQL_ASSOC);
////    $baseSource = $basePath."/stemmi/A072";
////    $source = $baseSource."/Stemma_Gestore_F902_2018-04-26.jpg";
//    while($riga = mysql_fetch_assoc($result))
//	{
//
//        unset($resultPar['ID']); //Remove ID from array
//        unset($resultPar['CC']); //Remove ID from array
//        unset($resultPar['Restituzione2']);
//        $qrystr = "INSERT INTO parametri_generali ";
//        $qrystr .= " ( CC, Restituzione2 ," .implode(", ",array_keys($resultPar)).") ";
//        $qrystr .= " VALUES (\"".$riga['CC']."\",\"COMUNE DI ".strtoupper($riga['Denominazione'])."\",\"".implode("\", \"",array_values($resultPar)). "\")";
//
//
//        mysql_query($qrystr);
////            $qrystr = "UPDATE parametri_annuali SET CAN=0 WHERE CC='".$riga['CC']."' AND Anno=2018";
////
////            mysql_query($qrystr);
//
//
//
////        $baseDestination = $basePath."/stemmi/".$riga['CC'];
////
////        crea_dir($baseDestination);
//
////        $nomeFile = "Stemma_Gestore_".$riga['CC']."_2018-04-26.jpg";
//////        $destination = $baseDestination."/".$nomeFile;
////
////
////        $query = "UPDATE gestore SET Stemma='".$nomeFile."' ";
////        $query.= "WHERE ID='".$riga['Gestore_ID']."' ";
////        $result2 = mysql_query($query);
//
//
//
////        copy($source, $destination);
//
//
//
////        $query = "SELECT * FROM parametri_responsabili WHERE CC='A072' AND Tipo_Email='PEC' ";
////        $result2 = mysql_query($query);
////        $resultPar = mysql_fetch_array($result2,MYSQL_ASSOC);
////
////        unset($resultPar['ID']); //Remove ID from array
////        unset($resultPar['CC']); //Remove ID from array
////        $qrystr = "INSERT INTO parametri_responsabili ";
////        $qrystr .= " ( CC," .implode(", ",array_keys($resultPar)).") ";
////        $qrystr .= " VALUES ('".$riga['CC']."','".implode("', '",array_values($resultPar)). "')";
////        mysql_query($qrystr);
//
////        $query = "SELECT * FROM parametri_testo_ingiunzione WHERE CC='A072' ORDER BY ID DESC LIMIT 1";
////        $result3 = mysql_query($query);
////        $resultTxt = mysql_fetch_array($result3,MYSQL_ASSOC);
////
////        unset($resultTxt['ID']); //Remove ID from array
////        unset($resultTxt['CC']); //Remove ID from array
////        unset($resultTxt['Data_Creazione_Parametri']); //Remove ID from array
////        $qrystr = "INSERT INTO parametri_testo_ingiunzione ";
////        $qrystr .= " ( CC,Data_Creazione_Parametri," .implode(", ",array_keys($resultTxt)).") ";
////        $qrystr .= ' VALUES ("'.$riga['CC'].'","2018-09-19","'.implode('", "',array_values($resultTxt)). '")';
////
////        mysql_query($qrystr);
//    }
//
////	$query = "SELECT * FROM pignoramento_generale ORDER BY Partita_ID ASC";
////
////	$result = mysql_query($query);
////
////	while($riga = mysql_fetch_assoc($result))
////	{
////		$partita = new partita($riga['Partita_ID'],$riga['CC']);
////		$ID_Avviso = $partita->ultimo_avviso;
////
////		$atto = new atto($ID_Avviso, $riga['CC']);
////		$rimanenza = $atto->dovuto_senza_pagamenti();
////		$dovuto = $rimanenza['totale'];
////
////		$query = "UPDATE pignoramento_generale SET Atto_ID = '".$atto->ID."', Importo_Dovuto = '".$dovuto."', ";
////		$query.= "Totale_Dovuto = ( Totale_Spese_Accessorie + Totale_Spese_Notifica + ".$dovuto.") ";
////		$query.= "WHERE ID = '".$riga['ID']."'";
////
////		$control = mysql_query($query);
////
////		if($control)
////		{
////
////		}
////		else
////			alert(mysql_error());
////
////	}
//
//
//	mysql_query('COMMIT');
//
//	alert('Fine modifica dati!');
	
?>